### ISSUE TITLE
build script doesn't build styles

### ISSUE THREAD

**Issue by homsar** [very-scary-scenario/idol-threat#11]
index.html refers to style.css, which doesn't exist—but style.less does. Moving style.less to style.css lets the stylesheet be loaded.

**Comment by colons** [comment]
im gonna make the build scripts include some equivalent of `lessc style.less > style.css` before we 'ship' this thing, but also wait does your browser natively support less?

**Comment by homsar** [comment]
I had no idea less was something distinct from CSS until I read your message; I don't know the canonical appearance of the page, so all I noticed was that when I renamed the file I went from no styles to some styles.

I also had a problem with getting the game to do anything with the images I add—presumably this is related. I'll try using lessc tonight and see if it helps.
