### ISSUE TITLE
Training: Surface average stats and give some feedback on whether that's good or bad 

### ISSUE THREAD

**Issue by theshillito** [very-scary-scenario/idol-threat#111]

**Comment by colons** [comment]
might be worth making the idol list view in the training interface include some indication of good or bad too, so you don't have to check all of them, but here's one basic idea

![img_0372](https://user-images.githubusercontent.com/1394710/50223834-25755380-0394-11e9-8154-2a8b8eeba4b0.jpg)
![img_0371](https://user-images.githubusercontent.com/1394710/50223835-25755380-0394-11e9-8c75-400886662593.jpg)

**Comment by theshillito** [comment]
I've mentioned before that having a grid of icons isn't great on the training interface, as you're probably looking for a specific name, but having a 🔼 or 🔽 to indicate average stat changes would prolly help

**Comment by euricaeris** [comment]
This also covers #27 and #109. Also, let's go per-stat so we can get everything we need to know at a glance:

<img width="243" alt="ataglance" src="https://user-images.githubusercontent.com/2502449/50224715-77b77400-0396-11e9-9521-393a2fb906cd.png">

**Comment by colons** [comment]
![an attempt to implement that mockup](https://user-images.githubusercontent.com/1394710/69915148-bf1dff80-1443-11ea-924b-82ad72bf0f99.png)
