### ISSUE TITLE
Idol Threatstival rank-up messages are a bit broken

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#115]
At the very least when a single member of my unit is knocked out and I win the battle, the text is a bit messy (rank 2 higher up took me far too long to parse and also we should just tell them what the rank number is, honestly) and I gain 0 experience (which I don't think should be possible in any winning situation, and shouldn't be mentioned at all for a loss?).

**Comment by colons** [comment]
I'm just gonna omit experience from this message; the experience cited in that message doesn't include anything gained in the actual fight. This makes no sense and is confusing, rank is what matters.
