### ISSUE TITLE
Wait half of a second (or so) before displaying idol stats in combat when pressing an idol

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#116]
Tapping an enemy to target and having their stats flash very briefly when I do so is far more annoying than it has any right to be. It's still a good feature but if we could delay it a bit so that it only shows up when we actually want it to show up, that'd be neat.

**Comment by colons** [comment]
>tapping an enemy idol to target them just forces the stats up without holding now
@euricaeris, pointing out that i broke it
