### ISSUE TITLE
Make attacks worth using

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#19]
With the fights being 3v3, it's pretty disappointing that there's no current benefit for using more than 1 move (the strongest), 2 at a stretch if you happen to have a healing move. There's no strategy beyond 'hit one of them until they die, then hit the next one'. 

I think that at the same time the attack names are generated, they should each be assigned one of three 'colours'. At the same time, the idol themselves should have a colour when generated. We then have a simple 'weapon triangle', which means we now have reasons to use one move over another, who you're using it against, and a reason to create a good, balanced team. 

So, as an example: your opponent has two green units and a red unit. I have a blue unit (which for the sake of the example is weak to red attacks) and thus it's in my best interests to remove the red unit as a priority.

In this example, red beats blue, blue beats green, green beats red. As far as the game goes, attacks will do 80%/100%/120% damage based on the colour of the attack versus the colour of the target. An extra 30% for an attack made by an idol of the same colour as the attack, for a max hit of 150% against a weak enemy.

If attacks are colour coded, we would want the colour triangle to be visible on the battle screen, or at least viewable in-battle (edit: actually, we might be able to get away with visual feedback when you've selected an attack, as the idols you can target could show whether it's strong against them or not). At the same time, it allows us to give a fourth colour to healing moves, so we can see what they are without trial and error. 

In-game, we just refer to these 'colours' as different characteristics. So for example, red could be 'bossy' idols, etc.

**Comment by colons** [comment]
resolved in 76e1a5c809245bb289ad1da5e171eaa3e1cae7cb with a very literal 'rock, paper, scissors', as suggested by @okand 

seems silly, but saves us a lot of trouble tutorialising, maps nicely to pokemon base type colours, and actually kinda makes sense for idols
