### ISSUE TITLE
Throw a Kira Ball™ to catch a wild idol

### ISSUE THREAD

**Issue by theshillito** [very-scary-scenario/idol-threat#20]

**Comment by colons** [comment]
i understand that @theshillito is sad that we no longer get to see the layers of idols as they load in, but they also suggested that we use the catching/hiring/auditioning UI (whatever this issue becomes) as a place to deliberately show each individual layer gradually appearing on top of the last

this is an idea i am very much into

**Comment by colons** [comment]
as of f5d812590d18f3f9e7cf786cd152920f02a58cbb we have some progress on this; layers load in and there's a 'recruit' button, but no real animation or anything
