### ISSUE TITLE
You should get a strong idol for scanning any version of the 2014 classic, "Jack Ryan: Shadow Recruit"

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#23]
**Name:** Jack Ryan
**Type:** Various (we should make the DVD/Blu-ray/Special? give diff colours but otherwise the same idol)
**Stats:** 100 in all stats
**Bio:** Somebody tried to kill them. Lied to their wife for three years. Didn't give their PhD. 
**Quote:** Now, talk me through your very scary scenario.
**Moves:**
- Play Rough (red)
- Geopolitics (blue)
- American directness (green)
- Very Scary Scenario (on-colour)

**Comment by colons** [comment]
does anyone know the best place to get a complete list of UPC codes for all variants of a particular release like this? the amazon API, perhaps?

**Comment by euricaeris** [comment]
https://www.barcodelookup.com/jack-ryan-shadow-recruit

This has a shit load of them, so we're probably good if we pinch the barcode numbers from here?
