### ISSUE TITLE
Consider swapping Endurance for something else, perhaps Luck

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#25]
As mentioned by @colons in a previous discussion, we may want to consider swapping endurance for another stat, as it's pretty similar to defence. If we do this, I propose we use luck instead. What that could possibly effect:

- Critical hit chance (hey we should probably have crits)
- Dodge chance (cautious on this as we shouldn't aim for battles to be longer)
- Bonus stat points for defeating an idol (maybe?)

Thoughts welcome!

**Comment by colons** [comment]
i'm in favour of removing endurance entirely. if we can come up with some good mechanical reason for having another, fourth stat, that's kind of a separate issue. right now, having two durability-related stats is just making the maths bad
