### ISSUE TITLE
Track some feeding/kill/graduation stats

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#26]
As I was feeding trash idols to my team last night, I realised it would have been quite nice to see how many idols she'd eaten. Something in-line with the rarity on the idol stats screen? I think it'll add a nice bit of extra context when we have people showing off idols that have finished the campaign.

It could also be nice to see total kills, or a win/lose ratio, but I don't think these are as important. 

I think graduations should also be tracked. The way I see this done is that, on the graduation stats screen, we have something like "Welcome to the Xth graduation ceremony", for a bit of flavour and an indication of how many prior graduations there have been.

**Comment by colons** [comment]
agency experience should cover this basic need for a record of progression
