### ISSUE TITLE
The feeding stats screen should clarify how much a stat is being raised/lowered by

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#27]
This is obviously not a huge issue when a calculation has a positive integer involved, but when there's a halved negative integer involved, I've found myself doing basic maths in my head to see if the loss of 10-20 points in one stat is worth the boost to another stat.

I'm seeing this as smaller numbers to the right of the 'new stats', with green/red colour coding to show positive/negative changes.

**Comment by colons** [comment]
I'm confident that this has been closed in #111.
