### ISSUE TITLE
Let me save an image of my team and their stats

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#28]
I think that when people really dig into the game, they're going to want to pump out some images of their main three. Instead of having to deal with three separate images (and manually getting them), it'd be nice if we could essentially do screen grabs of each of the three's stat screens, then stitch them into one large image to make it easier to share.

**Comment by theshillito** [comment]
Perhaps expand this to a "team photo" thing, with an option to include stats or not. If I find three idols who look great together, I'd like a photo-type thing where there's a zoomed out shot of the three together on a stage or something...

**Comment by euricaeris** [comment]
Stats being optional is a good shout. Gotta be careful re: zoomed out shots as our idols don't have legs.

**Comment by theshillito** [comment]
use a crowd of people to cover the lack of legs?

**Comment by colons** [comment]
cropping seems like it'd be okay for this, but i think if i was gonna do this i'd just want to make the unit overview look as nice as possible so that people's screenshots would look good

perhaps related: #7
