### ISSUE TITLE
Beating the story mode units should give you larger bonuses

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#30]
The running joke in the story is that you are consuming the idols. While actually consuming the idols re: stats would be bad, we should offer more than +1 per idol for the effort. 

Thinking out loud, the # of points that are randomly assigned could be 'the stage of the story' x 'the number of times you've beaten the story+1'. So 5 points for chapter 5, 15 points for chapter 5 second playthrough, etc.

**Comment by colons** [comment]
We now do this for agency experience, at least in the later story chapters. Is that enough?

**Comment by euricaeris** [comment]
I still think we should. It'd take a while for bonuses to catch up at the rate that enemies are getting stronger by (currently 50 points to each stat per chapter for the bosses, versus 1 random point for you per idol). 

Feeding is always going to be the best way to get stats, but 1 point is pretty meaningless. When the agency is in, even the worst graduation will give you more than that. Perhaps we make the bonus you receive off a win tied to something you can upgrade in the agency?

There is some balancing to take into account, as you say. Testing required I think.

**Comment by colons** [comment]
I'm a little unsure how we would surface that this has happened.
