### ISSUE TITLE
names never contain sokuon

### ISSUE THREAD

**Issue by colons** [very-scary-scenario/idol-threat#34]

**Comment by euricaeris** [comment]
Romanising sokuon seems like it'd be a big pain in the ass, and for people that don't know enough about how Japanese names work, they'd probably look less Japanese. I'd be in favour of just not bothering.

**Comment by colons** [comment]
what seems difficult about it? i thought for the most part it'd just mean repeating the first letter of the picked kana with a few little special cases for `chi` and such

**Comment by euricaeris** [comment]
Hmm, okay. Looked like it was more complicated than that but fair enough. The latter point still stands though. I don't really think we need to worry about romanised accuracy when this thing already pumps out garbage anyway.
