### ISSUE TITLE
Don't show idols that are in your current unit when selecting who to train with

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#35]

**Comment by colons** [comment]
i feel like there are a _lot_ of things we need to think about in the training UI, but this is certainly one of them

not sure if hiding them altogether is the right thing, but making it clear one way or the other is definitely important

**Comment by euricaeris** [comment]
![bad mockup](https://user-images.githubusercontent.com/2502449/29416052-d5ed39c6-835c-11e7-9050-a5c15cfbe140.png)

Something I made to separate folks in-unit and those not. Also, while #54 will have some effect on this, it's a separate issue.

**Comment by colons** [comment]
we still probably want to revisit a lot about the training interface, but as of #54, this is technically done
