### ISSUE TITLE
credits?

### ISSUE THREAD

**Issue by theshillito** [very-scary-scenario/idol-threat#44]
![credits](https://cloud.githubusercontent.com/assets/1828418/26575160/f5170fea-451b-11e7-92a8-19fc498c107a.png)

¯\\_(ツ)_/¯

**Comment by euricaeris** [comment]
We have a main menu so we should

**Comment by theshillito** [comment]
Agreed. Also, digi's been making art for this game since forever and MUST BE PRAISED 🙇‍♀️
