### ISSUE TITLE
Solve the crashing that can happen when recruiting an idol

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#51]
For me, it's typically happening on every second idol. However, I remember it being one in every 10 or so, and has reduced over time. Might be related to how much I've played?

The crashes happen on the idol pop-in screen. On some occasions, the idol doesn't register and has to be rescanned upon reloading the app. This is quite rare, though. 

Something I have noticed is that I can tell if it's about to crash, because the layer load-in slows right down, and it seems to keep happening when loading in the eyes. Might be coincidence though.

**Comment by colons** [comment]
i have looked into this a little bit, and i think it's not necessarily something we can control; looking at logs of these events points at a consistent segfault, which definitely shouldn't be possible with a web app

unfortunately, safari's remote debugger crashes alongside the webview when this happens, and the report outputted isn't, as i understand it, super useful without access to the safari source code

still, this is definitely a real problem and we should do our best to solve it

**Comment by euricaeris** [comment]
While the crashing is happening consistently (for me) on the screen where the new idol pops in, I've noticed there's about a 20% chance that the new idol isn't in your agency when you load the app back up. No idea why this only happens occasionally, but wanted to mention it.
