### ISSUE TITLE
Tapping through the story mode sometimes brings up the idols that are behind it

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#56]
and because there's some weird layer stuff going on (I think?) it's pretty fun trying to get back to the story.

**Comment by colons** [comment]
I _think_ this might have been solved in 126e4fe6d627aaf0b32f3e5141991da74802d4af; please lmk if you run into it again.

**Comment by euricaeris** [comment]
Pretty sure this isn't an issue any more
