### ISSUE TITLE
when running in home screen app mode, idol threat cannot access the camera on ios 11

### ISSUE THREAD

**Issue by colons** [very-scary-scenario/idol-threat#73]
this may be a beta exclusive, but it's been true for at least developer betas 7 and 8, and i just want to keep an eye on it.

**Comment by colons** [comment]
this is still the case on developer beta 9

**Comment by colons** [comment]
I've filed this with Apple, referencing <https://colons.co/photo-upload/> (which I've also attached as an html file in case they are nervous about hitting some rando's server). It has been assigned radar number 34209726.

**Comment by colons** [comment]
They closed this as a duplicate of radar 34059209.

**Comment by colons** [comment]
still present in developer beta 10, and im starting to get very worried that this might not be fixed for the GM, given that it's probably gonna be shipping on tuesday next week

**Comment by colons** [comment]
if anyone's feeling brave enough to install that leaked ios 11 GM on their devices, feel free to test this on it

**Comment by colons** [comment]
probably worth noting that this is no longer an option; apple's refusing to authorise installs of the leaked version now

**Comment by colons** [comment]
still present in the GM seed, have updated the apple ticket

**Comment by colons** [comment]
> Thank you for contacting us. It has not been determined how or when the issue will be resolved.

**Comment by colons** [comment]
first beta of 11.1 is out, and it still exhibits this issue

**Comment by theshillito** [comment]
I hate to be _that person_, but do you think it would be worth considering how to approach this in the event Apple **don't** fix this?

**Comment by colons** [comment]
This is fixed in 11.3 developer beta 2. Here's hoping it stays that way in the final release!

**Comment by euricaeris** [comment]
Fixed in iOS 11.3
