### ISSUE TITLE
a way to look at idol art without interface and stats on top of 'em

### ISSUE THREAD

**Issue by colons** [very-scary-scenario/idol-threat#91]
this would probably be reached by tapping the art on the idol detail screen to just go full-screen with the rendered art on a clean, affinity-coloured background

also gives us a fun opportunity to promote the game by watermarking it somehow

**Comment by theshillito** [comment]
see also https://github.com/very-scary-scenario/idol-threat/issues/28

**Comment by colons** [comment]
yeah, this is just #28
