### ISSUE TITLE
Hitting the fight button without picking an attack doesn't tell you off

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#95]
This is for the story mode and quick battle on Android. The leftmost enemy idol is also strangely highlighted in the process.

**Comment by colons** [comment]
![select one of these options](https://user-images.githubusercontent.com/1394710/69914049-8d9f3700-1437-11ea-9cf7-3584e4dee27b.png)
It's trying to show you the radio buttons, but they're very off-screen.
