### ISSUE TITLE
The screens after scanning a new idol run like butt

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#98]
The sparkle effect might be the culprit? Either way, the scene in which the new idol pops in bit by bit really chugs.

**Comment by theshillito** [comment]
They aren't great on my phone either. Perhaps instead of sparkles everywhere it could just be a sparkly overlay (a progress bar but made of stars) which then vanishes when it's finished loading?

**Comment by euricaeris** [comment]
Smooth and nice
