### ISSUE TITLE
All idols face towards the right

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/idol-threat#99]
Maybe we should mirror enemy characters so it looks a bit more like they're on the other side?

**Comment by okand** [comment]
All the assets that have text in them won't look any good from just being mirrored though.

**Comment by theshillito** [comment]
On the one hand there's an issue with text on t-shirts being backwards if we mirror the images.

On the other hand the text on t-shirts are backwards if we mirror the images.

**Comment by euricaeris** [comment]
I goofed by not thinking of t-shirt text, so closing this
